import PDFDocument from "pdfkit";

// ─── Brand tokens ─────────────────────────────────────────────────────────────

const C = {
  indigo:      "#241B3A",
  gold:        "#B8860B",
  cream:       "#FBF5EA",
  creamBorder: "#E8DFC8",
  creamMid:    "#F5E9D0",
  muted:       "#6B6080",
  white:       "#FFFFFF",
  grey:        "#9CA3AF",
} as const;

const TIER = {
  ideal:   { bg: "#F0FDF4", text: "#166534", label: "Ideal" },
  okay:    { bg: "#FFFBEB", text: "#92400E", label: "Acceptable" },
  neutral: { bg: "#F8FAFC", text: "#475569", label: "Neutral" },
  avoid:   { bg: "#FEF2F2", text: "#991B1B", label: "Needs Attention" },
} as const;

const VERDICT_COLOR = {
  Excellent: "#16A34A",
  Good:      "#D97706",
  Fair:      "#EA580C",
  Poor:      "#DC2626",
} as const;

// ─── Types ────────────────────────────────────────────────────────────────────

export type RoomFinding = {
  room: string;
  label: string;
  direction: string;
  tier: "ideal" | "okay" | "neutral" | "avoid";
  points: number;
  remedy: string;
};

export type VaastuReportInput = {
  homeLabel: string;
  scoredAt: string;
  score: number;
  verdict: "Excellent" | "Good" | "Fair" | "Poor";
  findings: RoomFinding[];
};

// ─── Layout constants ─────────────────────────────────────────────────────────

const PW  = 595.28;   // A4 width in pt
const PH  = 841.89;   // A4 height in pt
const MX  = 40;       // horizontal margin
const CW  = PW - MX * 2; // content width
const FH  = 56;       // footer band height

// ─── Helpers ─────────────────────────────────────────────────────────────────

function drawFooter(doc: PDFKit.PDFDocument) {
  const fy = PH - FH;
  doc.rect(0, fy, PW, FH).fill(C.indigo);

  doc.font("Helvetica")
    .fontSize(6.8)
    .fillColor(C.creamMid)
    .text(
      "This report is prepared for guidance purposes only and reflects classical Vastu Shastra principles. " +
      "VaastuSetu recommends consulting a qualified Vastu expert before making structural changes. " +
      "No liability is accepted for decisions made on the basis of this report.",
      MX, fy + 9,
      { width: CW, align: "center", lineBreak: true }
    );

  doc.font("Helvetica-Bold")
    .fontSize(7.5)
    .fillColor(C.gold)
    .text(
      "vaastusetu.com  ·  Generated by VaastuSetu",
      MX, fy + 38,
      { width: CW, align: "center", lineBreak: false }
    );
}

// ─── Main generator ──────────────────────────────────────────────────────────

export function generateVaastuPDF(input: VaastuReportInput): Promise<Buffer> {
  const { homeLabel, scoredAt, score, verdict, findings } = input;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 0,
      info: {
        Title:   `VaastuSetu Report — ${homeLabel}`,
        Author:  "VaastuSetu",
        Subject: "Vastu Score Report",
      },
      // Disable automatic page adding so we control layout
      autoFirstPage: true,
    });

    const chunks: Buffer[] = [];
    doc.on("data",  (c: Buffer) => chunks.push(c));
    doc.on("end",   () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    let y = 0;

    // ── Header band ───────────────────────────────────────────────────────
    const HEADER_H = 82;
    doc.rect(0, 0, PW, HEADER_H).fill(C.indigo);

    doc.font("Helvetica-Bold")
      .fontSize(26)
      .fillColor(C.cream)
      .text("VaastuSetu", MX, 24, { lineBreak: false });

    doc.font("Helvetica")
      .fontSize(8)
      .fillColor(C.gold)
      .text("ANCIENT WISDOM  ·  MODERN HOMES", MX, 57, {
        lineBreak: false,
        characterSpacing: 1.2,
      });

    y = HEADER_H + 22;

    // ── Home label ────────────────────────────────────────────────────────
    doc.font("Helvetica-Bold")
      .fontSize(20)
      .fillColor(C.indigo)
      .text(homeLabel, MX, y, { width: CW, lineBreak: false });

    y += 28;

    doc.font("Helvetica")
      .fontSize(9)
      .fillColor(C.muted)
      .text(`Vastu Score Report  ·  ${scoredAt}`, MX, y, { lineBreak: false });

    y += 24;

    // ── Score card ────────────────────────────────────────────────────────
    // Stacked vertically: large number → "out of 100" → verdict
    const SCORE_CARD_H = 90;
    doc.roundedRect(MX, y, CW, SCORE_CARD_H, 6)
      .fillAndStroke(C.white, C.creamBorder);

    doc.font("Helvetica-Bold")
      .fontSize(50)
      .fillColor(C.indigo)
      .text(String(Math.round(score)), MX + 20, y + 10, { lineBreak: false });

    doc.font("Helvetica")
      .fontSize(9)
      .fillColor(C.muted)
      .text("out of 100", MX + 20, y + 62, { lineBreak: false });

    doc.font("Helvetica-Bold")
      .fontSize(16)
      .fillColor(VERDICT_COLOR[verdict])
      .text(verdict, MX + 20, y + 74, { lineBreak: false });

    y += SCORE_CARD_H + 18;

    // ── Divider — plain line, no character ───────────────────────────────
    doc.moveTo(MX, y + 5)
      .lineTo(PW - MX, y + 5)
      .strokeColor(C.creamBorder)
      .lineWidth(0.8)
      .stroke();

    y += 20;

    // ── Section heading ───────────────────────────────────────────────────
    doc.font("Helvetica-Bold")
      .fontSize(13)
      .fillColor(C.indigo)
      .text("Room-by-Room Breakdown", MX, y);

    y += 20;

    // ── Room cards ────────────────────────────────────────────────────────
    const PAGE_BOTTOM = PH - FH - 10;

    for (const f of findings) {
      const tier = TIER[f.tier];

      // Pre-calculate remedy height
      const remedyInnerW = CW - 32;
      const remedyH = f.remedy
        ? doc.font("Helvetica").fontSize(8.5).heightOfString(f.remedy, { width: remedyInnerW }) + 14
        : 0;
      const cardH = 32 + remedyH;

      // Page break
      if (y + cardH > PAGE_BOTTOM) {
        drawFooter(doc);
        doc.addPage({ size: "A4", margin: 0 });
        y = 20;
      }

      // Card background
      doc.roundedRect(MX, y, CW, cardH, 5)
        .fillAndStroke(C.white, C.creamBorder);

      // Room name
      doc.font("Helvetica-Bold")
        .fontSize(10)
        .fillColor(C.indigo)
        .text(f.label, MX + 12, y + 10, { lineBreak: false });

      const nameW = doc.widthOfString(f.label);

      // Direction (after room name with gap)
      doc.font("Helvetica")
        .fontSize(9)
        .fillColor(C.muted)
        .text(f.direction, MX + 12 + nameW + 6, y + 11, { lineBreak: false });

      // Points (right-aligned)
      const ptsText = `${f.points.toFixed(1)} pts`;
      doc.font("Helvetica")
        .fontSize(8)
        .fillColor(C.grey)
        .text(ptsText, PW - MX - 44, y + 12, { lineBreak: false, width: 40, align: "right" });

      // Tier pill (to the left of points)
      const pillLabel = tier.label;
      const pillW = doc.font("Helvetica-Bold").fontSize(8).widthOfString(pillLabel) + 12;
      const pillX = PW - MX - 44 - pillW - 6;

      doc.roundedRect(pillX, y + 8, pillW, 14, 4).fill(tier.bg);
      doc.font("Helvetica-Bold")
        .fontSize(8)
        .fillColor(tier.text)
        .text(pillLabel, pillX + 6, y + 11.5, { lineBreak: false });

      // Remedy box
      if (f.remedy) {
        const remY = y + 28;
        const remH = cardH - 32;
        doc.roundedRect(MX + 10, remY, CW - 20, remH, 3).fill(C.creamMid);
        doc.font("Helvetica")
          .fontSize(8.5)
          .fillColor("#374151")
          .text(f.remedy, MX + 17, remY + 6, {
            width: remedyInnerW,
            lineBreak: true,
          });
      }

      y += cardH + 8;
    }

    // ── Footer on last page ───────────────────────────────────────────────
    drawFooter(doc);

    doc.end();
  });
}
